### ISSUE TITLE
A LOT of errors in the log

### ISSUE THREAD

**Issue by mgzenitech** [rebuy-de/aws-nuke#1003]
Logs attached. This is with **root** user access key and secret key.
[aws-nuke.filtered.log](https://github.com/rebuy-de/aws-nuke/files/11529998/aws-nuke.filtered.log)

Config is pretty simple:
```yaml
regions:
- global
- us-east-2
- us-east-1
- us-west-1
- us-west-2
- af-south-1
- ap-east-1
- ap-south-1
- ap-northeast-3
- ap-northeast-2
- ap-southeast-1
- ap-southeast-2
- ap-northeast-1
- ca-central-1
- eu-central-1
- eu-west-1
- eu-west-2
- eu-south-1
- eu-west-3
- eu-north-1
- me-south-1
- sa-east-1
feature-flags:
  disable-deletion-protection:
    RDSInstance: true
    EC2Instance: true
    CloudformationStack: true
  force-delete-lightsail-addons: true
account-blocklist:
- 999999999999
accounts:
  xxxxxxxxxx:
    filters:
      ....
```
