### ISSUE TITLE
Filter with date not working

### ISSUE THREAD

**Issue by quentin9696** [rebuy-de/aws-nuke#1011]
Hi, 

I try to use the date filter but it's not working. 

Here is my config: 
``` yaml
regions:
- us-east-1

account-blocklist:
- "999999999999" # production

accounts:
  "111111111111":
    filters:
      EC2Instance:
        - property: "tag:Delete"
          type: dateOlderThan
          value: 2022
```

I run it in the latest version of the container image

``` text
version:     v2.22.1.14.g02900da
build date:  Sun May 28 03:20:21 UTC 2023
scm hash:    02900da185e81d60a15c039c8d004dd302644e1b
environment: root@buildkitsandbox
go version:  go1.20.4
```

And here is the error: 

``` text
Error: time: missing unit in duration "2022"
```         

And here is the tag on my machine: 
![image](https://github.com/rebuy-de/aws-nuke/assets/14543538/ec8848b6-dd0c-4427-8903-7d075ccb77e3)

Any idea?

**Comment by abdulalloy** [comment]
valid time units for the offset in the config are either "ns", "us" (or "µs"), "ms", "s", "m", "h".

so in your config you should have it like:
```
regions:
- us-east-1

account-blocklist:
- "999999999999" # production

accounts:
  "111111111111":
    filters:
      EC2Instance:
        - property: "tag:Delete"
          type: dateOlderThan
          value: 24h # if you want the resource to be deleted after a day
```

in the resource tag the valid date formats are listed in the readme: 
```
1582735862 (seconds since epoch)
2006-01-02
2006/01/02
2006-01-02T15:04:05Z
2006-01-02T15:04:05.999999999Z07:00
2006-01-02T15:04:05Z07:00
```
so for you it can be something like `Delete:2023-06-08` and this resource will be deleted because of the 24h (1d) config
I hope this makes sense.
