### ISSUE TITLE
How can I exclude deleting of Cloudwatch group?

### ISSUE THREAD

**Issue by agroyz** [rebuy-de/aws-nuke#1035]
such configuration is not working. the two groups are still nuked. probably i need to exclude log streams, but how?

CloudWatchLogsLogGroup:
          - property: "LogGroupName"
            value: "cloudtrail-logs2"
          - property: "LogGroupName"
            value: " cloudtrail-logs1"

**Comment by npellegrin** [comment]
Hello @agroyz 

You problem here is to have specified **"LogGroupName"** instead of **"logGroupName"** 😄 

When specifying a property filter, the case must be **exactly** the one supported in aws-nuke, otherwise it will be ignored. You can copy the attribute value from the aws-nuke scan output to prevent errors, for example, the correct case is shown here:

```
eu-west-1 - CloudWatchLogsLogGroup - /aws/lambda/test - [CreatedTime: "1687726966454", LastEvent: "2023-06-25T23:02:46+02:00", logGroupName: "/aws/lambda/test"] - would remove
```

Consequently, the below configuration will work:
```
regions:
- global
- eu-west-1

account-blocklist:
- 1234567890

accounts:
  1234567890:
    filters:
      CloudWatchLogsLogGroup:
      - property: "logGroupName"
        value: "/aws/lambda/test"
```

Note that you can also use the syntax without properties, because with CloudWatch log groups, the log group name is also the aws-nuke resource identifier (you can deduce this from the aws-nuke scan output as well). The below configuration will produce the same results:

```
regions:
- global
- eu-west-1

account-blocklist:
- 1234567890

accounts:
  1234567890:
    filters:
      CloudWatchLogsLogGroup:
       - "/aws/lambda/test"
```
