### ISSUE TITLE
How long does aws-nuke take to delete S3 bucket with 6 GB plus

### ISSUE THREAD

**Issue by venky6363** [rebuy-de/aws-nuke#1189]
How long does it take to delete s3 bucket with multiple objects inside multiple folders 
as i was doing a s3 bucket which has 6gb plus storage taking 8 plus hours to delete with below config file 

```

resource-types:
  targets:
  - S3Bucket


accounts:
  xxxxxxxxxxxxxx: 
    filters:
     S3Bucket:
      - "s3://xxxxxxxx-bucket"
```
