### ISSUE TITLE
Filtered Resources seem to get removed anyway

### ISSUE THREAD

**Issue by leflamm** [rebuy-de/aws-nuke#203]
Hi,

I have a configuration file with filtered resources

```yml
regions:
- eu-central-1

account-blacklist:
- "<prod account id>" # prod

accounts:
  "<some account id>": # stage12
  filters:
    CloudFormationStack:
    - "global-exports"
    [... snippet ...]
```

If I want to nuke the account I expected the `CloudFormationStack` "global-exports" to be ignored.
```
$ ./env-nuke -c nuke-stage12.yml
aws-nuke version v2.0.1 - Mon Jun  4 13:49:44 UTC 2018 - 5e5ffd21b7788364923546ab1e0aa6bfe234a56d

Do you really want to nuke the account with the ID <some account id> and the alias 'stage12'?
Do you want to continue? Enter account alias to continue.
> stage12

[... snippet ...]
eu-central-1 - CloudFormationStack - 'global-exports' - would remove
[... snippet ...]

Scan complete: 19 total, 7 nukeable, 12 filtered.
Would delete these resources. Provide --no-dry-run to actually destroy resources.
```
**Still `aws-nuke` wants to remove it. What am I doing wrong?**

Just FYI - the wrapper script `env-nuke`
```sh
#!/bin/bash

NUKE_BIN="/home/cf/opt/aws-nuke-v2.0.1-linux-amd64"

[ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ] && {
	echo "AWS environment missing. Exiting!"
	exit 1
}

$NUKE_BIN --access-key-id $AWS_ACCESS_KEY_ID --secret-access-key $AWS_SECRET_ACCESS_KEY --session-token $AWS_SESSION_TOKEN $*
```

**Comment by tomvachon** [comment]
Can you please do `-t CloudFormationStack -v` and provide the verbose output?

**Comment by leflamm** [comment]
@tomvachon , any way I can provide it not publicly? Thx!

**Comment by svenwltr** [comment]
I created a PR (#204) that enable strict config parsing. Maybe there is an issue with the config file which gets swallowed.

I'll create a release (or pre-release) after merging.

**Comment by leflamm** [comment]
Cool

**Comment by svenwltr** [comment]
@leflamm Could you try it again with [v2.1.0-beta.1](https://github.com/rebuy-de/aws-nuke/releases/tag/v2.1.0-beta.1)?

**Comment by leflamm** [comment]
Done. Seems to be the right spot to look at!
```
AFP|admin@stage12 $ ./env-nuke -c nuke-stage12.yml 
ERRO[0001] Failed to parse config file.                 
Error: yaml: unmarshal errors:
  line 10: field CloudFormationStack not found in type config.Account
  line 25: field LambdaFunction not found in type config.Account
```

Looking for typos...
```
AFP|admin@stage12 $ ./env-nuke resource-types | egrep -i "(cloudformation|lambda)"
CloudFormationStack
LambdaFunction
```

... nope looks good. Snippet from `nuke-stage12.yml`

```yml
regions:
- eu-central-1

account-blacklist:
- <prod account> # prod

accounts:
  <stage account>: # stage12
  filters:
    CloudFormationStack:
    - "global-exports"
    - < .... some more>
    LambdaFunction:
    - < ... some more>

resource-types:
  excludes:
    - EC2Subnet
    - EC2DHCPOption
    - ACMCertificate
    - KMSKey
    - KMSAlias
    - EC2NetworkACL
    - EC2NATGateway
    - EC2VPC
    - EC2Address
    - EC2InternetGateway
    - OpsWorksUserProfile
    - EC2InternetGatewayAttachment
    - EC2SecurityGroup
    - EC2RouteTable
```
