### ISSUE TITLE
Question: glob/regex matching Resources without Properties

### ISSUE THREAD

**Issue by leflamm** [rebuy-de/aws-nuke#219]
Hi,

the project documentation shows how to match resources using blog/regex expression based on one of their properties:
```yml
Route53HostedZone:
- property: Name
  type: glob
  value: "*.rebuy.cloud."
```
How can I do that with resources that don't seem to have any explicit property like `global - IAMPolicy - 'arn:aws:iam::<some account>:policy/<some policy>' - would remove`

Is their a way to glob/regex match e. g. an `IAMPolicy` by matching its "id" here (seems to be its ARN).

Thanks, Christian

**Comment by svenwltr** [comment]
Yes, *aws-nuke* will filter by that ID, if you do not specify the `property` field. For `IAMPolicy` it would look like this:

```yaml
IAMPolicy:
- type: glob
  value: "arn:aws:iam::*:policy/uber-admin"
```
