### ISSUE TITLE
IAMPolicy identifier uses arn instead of id

### ISSUE THREAD

**Issue by n3ph** [rebuy-de/aws-nuke#297]
Greetings and thank you for this nice piece of code!

We have a Multi-Account using AssumeRoles and would like to filter out related objects in IAMRole, IAMPolicy, IAMRolePolicy and IAMRolePolicyAttachment. ATM aws-nuke seems to use the full ARN for IAMPolicy, which includes the AccountID.

It would be really nice to have the ResourceName instead of the ResourceARN to have the AccountID just defined once.

```yml
#------------------------------------------------------------------------------#
# Productive accounts
#------------------------------------------------------------------------------#

account-blacklist:
  - 012345678910 # NO ALIAS                      # Organization

#------------------------------------------------------------------------------#
# List of possible accounts to nuke
#------------------------------------------------------------------------------#

  - 012345678911 # org-devops
  - 012345678912 # org-test

#------------------------------------------------------------------------------#
# Nuke Example
#------------------------------------------------------------------------------#

# Hosting regions
regions:
  - global
  - eu-central-1

# Devops account
accounts:
  012345678911:
    filters:
      IAMRole:
        - "OrganizationAccountAccessRole"
        - "SwitchRoleCI"
        - "SwitchRoleOperator"
        - "SwitchRoleDeveloper"
        - "SwitchRoleReadOnly"
      IAMPolicy:
        - "arn:aws:iam::012345678911:policy/SwitchRoleCI"
        - "arn:aws:iam::012345678911:policy/SwitchRoleOperator"
        - "arn:aws:iam::012345678911:policy/SwitchRoleDeveloper"
        - "arn:aws:iam::012345678911:policy/SwitchRoleReadOnly"
        - "arn:aws:iam::012345678911:policy/SwitchRoleReadOnlyAdditional"
      IAMRolePolicy:
        - "OrganizationAccountAccessRole -> AdministratorAccess"
      IAMRolePolicyAttachment:
        - "AWSServiceRoleForOrganizations -> AWSOrganizationsServiceTrustPolicy"
        - "SwitchRoleCI -> SwitchRoleCI"
        - "SwitchRoleCI -> ReadOnlyAccess"
        - "SwitchRoleOperator -> ReadOnlyAccess"
        - "SwitchRoleOperator -> SwitchRoleOperator"
        - "SwitchRoleDeveloper -> ReadOnlyAccess"
        - "SwitchRoleDeveloper -> SwitchRoleDeveloper"
        - "SwitchRoleReadOnly -> ReadOnlyAccess"
        - "SwitchRoleReadOnly -> SwitchRoleReadOnlyAdditional"
```

**Comment by svenwltr** [comment]
Hello @n3ph,

unfortunately changing the name is not possible, because this would break the backward compatibility (ie anyone who defined an ARN here would have to change it to the name; and if anyone does not do this, their resources just get deleted). But there is a workaround and a long-term solution.

The workaround is to use globbing, like described in the readme. The resulting file could look like this (not tested):

```yaml
#------------------------------------------------------------------------------#
# Productive accounts
#------------------------------------------------------------------------------#

account-blacklist:
  - 012345678910 # NO ALIAS                      # Organization

#------------------------------------------------------------------------------#
# List of possible accounts to nuke
#------------------------------------------------------------------------------#

  - 012345678911 # org-devops
  - 012345678912 # org-test

#------------------------------------------------------------------------------#
# Nuke Example
#------------------------------------------------------------------------------#

# Hosting regions
regions:
  - global
  - eu-central-1

# Devops account
accounts:
  012345678911:
    filters:
      IAMRole:
        - "OrganizationAccountAccessRole"
        - "SwitchRoleCI"
        - "SwitchRoleOperator"
        - "SwitchRoleDeveloper"
        - "SwitchRoleReadOnly"
      IAMPolicy:
        - type: glob
          value: "arn:aws:iam::*:policy/SwitchRoleCI"
        - type: glob
          value: "arn:aws:iam::*:policy/SwitchRoleOperator"
        - type: glob
          value: "arn:aws:iam::*:policy/SwitchRoleDeveloper"
        - type: glob
          value: "arn:aws:iam::*:policy/SwitchRoleReadOnly"
        - type: glob
          value: "arn:aws:iam::*:policy/SwitchRoleReadOnlyAdditional"
      IAMRolePolicy:
        - "OrganizationAccountAccessRole -> AdministratorAccess"
      IAMRolePolicyAttachment:
        - "AWSServiceRoleForOrganizations -> AWSOrganizationsServiceTrustPolicy"
        - "SwitchRoleCI -> SwitchRoleCI"
        - "SwitchRoleCI -> ReadOnlyAccess"
        - "SwitchRoleOperator -> ReadOnlyAccess"
        - "SwitchRoleOperator -> SwitchRoleOperator"
        - "SwitchRoleDeveloper -> ReadOnlyAccess"
        - "SwitchRoleDeveloper -> SwitchRoleDeveloper"
        - "SwitchRoleReadOnly -> ReadOnlyAccess"
        - "SwitchRoleReadOnly -> SwitchRoleReadOnlyAdditional"
```

In the long-term, we plan to replace the identification of resources from a single string (eg `SwitchRoleDeveloper -> SwitchRoleDeveloper`) to using properties (eg `Role: SwitchRoleDeveloper, Policy: SwitchRoleDeveloper`). This will allow use to add additional properties at any time, but we did not fully implement this, yet.
