### ISSUE TITLE
Unable to nuke-cross account resources

### ISSUE THREAD

**Issue by theonkar10** [rebuy-de/aws-nuke#316]
I am trying to nuke cross-account resources.

I have 2 accounts, `prod` & `sandbox` account. EC2 instance with nuke setup is on prod account.
Using this I am trying to delete resources from my sandbox.

Below is my *.yaml file.

```
---
regions:
- "global" # This is for all global resource types e.g. IAM
- "ap-south-1"

account-blacklist:
-  "prod_account_id"#prod
# optional: restrict nuking to these resources
resource-types:
  targets:
  - S3Bucket
  - S3Object
  - Route53HostedZone
  - EC2Instance
  - CloudFormationStack

accounts:

 "sanbox_id": #sandbox
    filters:
      S3Bucket:
      - "s3://my-bucket"
      S3Object:
      - type: "glob"
        value: "s3://my-bucket/*"
      Route53HostedZone:
      - property: Name
        type: "glob"
        value: "*.zone.loc."
      CloudFormationStack:
      - property: "tag:team"
        value: "myTeam"

```
When I am trying to run nuke command I get error as per screenshot.

![yaml1](https://user-images.githubusercontent.com/38750623/51588658-cf537d00-1f0a-11e9-9b78-72a993c6ca91.PNG)

The account id I have highlighted is the prod account which is blacklisted account. Nuke is trying to delete the prod account and not sandbox account.

How do I get it working or is it due to  some mis-configuration? 

Using Go-Version 1.11.4
AWS Nuke build date:  Wed Jan 16 05:41:59 UTC 2019
