### ISSUE TITLE
Error: Your account ID 'xxxxxxxxxxxxx' isn't listed in the config.  Aborting

### ISSUE THREAD

**Issue by casey-robertson** [rebuy-de/aws-nuke#329]
Getting this error but the account ID is definitely in the referenced config file:

./aws-nuke -c ./config/mb.yaml --profile default

Confirmed from aws --profile default sts get-caller-identity the account matches.  What am I missing?

Per the instructions I did create an alias as specified under IAM - Customize for the login link.

**Comment by svenwltr** [comment]
Hello @casey-robertson,

it is hard to tell what is wrong without seeing the config.

I am using the config from the README as an example:

```yaml
regions:
- eu-west-1

account-blacklist:
- "999999999999" # production

accounts:
  "000000000000": # aws-nuke-example
    filters:
      IAMUser:
      - "my-user"
      IAMUserPolicyAttachment:
      - "my-user -> AdministratorAccess"
      IAMUserAccessKey:
      - "my-user -> ABCDEFGHIJKLMNOPQRST"
```

In your case it seems that the `000000000000` in the `accounts` part is missing.
