### ISSUE TITLE
EC2NetworkInterface Filter Issue - ec2-network-interfaces.go

### ISSUE THREAD

**Issue by jcare23** [rebuy-de/aws-nuke#357]
**Title:** “EC2NetworkInterface Filter - ec2-network-interfaces.go”
**Product:** “aws-nuke v2.9.0”
**Classification:** “Minor Bug”
**Platform:** “MacOs Mojave 10.14.4, GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)”
**Can it be reproduced?** “Every time”
**Description:**
-   **Summary:** "Ran aws-nuke with an EC2NetworkInterface Filter using the eni of the network interface and the dry-run shows -would remove.”
-   **What’s the error?:** “-would remove for filtered EC2NetworkInterface resources using the eni.”
-   **Steps to reproduce:** “Run aws-nuke with EC2NetworkInterface filtered with a network interface eni”
-   **Expected results:** “Filtered eni displays - filtered by config in dry-run output.”
-   **Actual results:** “- would remove”
-   **Workaround:** “Implement a filter for func (*EC2) DeleteNetworkInterface https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DeleteNetworkInterface"
-   **Attachments:**

**Comment by videte47** [comment]
@jcare23 I was able to properly filter a ENI successfully

```
us-east-1 - EC2NetworkInterface - [ID: "eni-0a315f8320d65da6e", VPC: "vpc-033d70b99cdf1499e", AvailabilityZone: "us-east-1a", PrivateIPAddress: "172.17.2.133", SubnetID: "subnet-05b3affd91975eb40", Status: "in-use"] - filtered by config
us-east-1 - EC2NetworkInterface - [PrivateIPAddress: "172.17.2.33", SubnetID: "subnet-0f8504ee106070c4c", Status: "in-use", ID: "eni-0d8822f17abb16115", VPC: "vpc-033d70b99cdf1499e", AvailabilityZone: "us-east-1a"] - would remove
Scan complete: 2 total, 1 nukeable, 1 filtered.
```
The above resources would be deleted with the supplied configuration. Provide --no-dry-run to actually destroy resources.

```
config.yaml:
accounts:
  12345676532: 
    filters:
      EC2NetworkInterface:
          - property: ID
            type: "glob"
            value: "eni-0a315f8320d65da6e"

resource-types:
    targets:
        - EC2NetworkInterface
```
