### ISSUE TITLE
Multiple Filters for same Resource Type

### ISSUE THREAD

**Issue by amitsehgal** [rebuy-de/aws-nuke#366]
Filtering by name on CloudFormationStack as the name gives error 

ERRO[0000] Failed to parse config file.
Error: yaml: unmarshal errors:
  line 15: key "CloudFormationStack" already set in map
```
   filters:
      CloudFormationStack:
        - type: contains
          property: Name
          value: "StackSet-AWS-Landing-Zone"
      CloudFormationStack:
        - type: contains
          property: Name
          value: "adf"       
```
Is there ORing or other type of syntax availavle to support multiple values for same resource type ?

**Comment by svenwltr** [comment]
Hello @amitsehgal 

It is possible to specify multiple filters. This is why `CloudFormationStack` contains a list ([beginning with the `-`](https://en.wikipedia.org/wiki/YAML)).

Your config should look like this:

```yaml
   filters:
      CloudFormationStack:
        - type: contains
          property: Name
          value: "StackSet-AWS-Landing-Zone"
        - type: contains
          property: Name
          value: "adf"  
```

The idea is that a resource is not removed, if is matches any of these filters match.
