### ISSUE TITLE
Error: field S3Bucket not found in type config.Account

### ISSUE THREAD

**Issue by pragya-nayak** [rebuy-de/aws-nuke#436]
Hi,

I want to exclude a bucket from all the deleting buckets and used below code. I am getting **error:  "field S3Bucket not found in type config.Account"** at filter: S3Bucket: 

I have referred https://github.com/rebuy-de/aws-nuke/blob/master/config/example.yaml
Can anyone please help me on this
``
regions:
  - global
  - us-east-1

account-blacklist:
  - "999999999999" # production

resource-types:
  targets:
  - S3Bucket
  - S3Object

accounts:
  000000000000:
  filter:
      S3Bucket:
      - "s3://bucket-name"
``

**Comment by svenwltr** [comment]
Hello @pragya-nayak,

it looks like the indentation of `filter` is wrong. Try this:

```yaml
regions:
  - global
  - us-east-1

account-blacklist:
  - "999999999999" # production

resource-types:
  targets:
  - S3Bucket
  - S3Object

accounts:
  000000000000:
    filter:
      S3Bucket:
      - "s3://bucket-name"
```
