### ISSUE TITLE
Support for Multi filters for one resource ?

### ISSUE THREAD

**Issue by opsrom** [rebuy-de/aws-nuke#437]
hello everyone, 

Is there a way to apply multiple filters on a resource? 
For example filters : 
- IAMRole named TOTO 
- and  IAMRoles that starts with "Admin" ? 

I can not find the right syntax ... 

PS: To filter an IAM SAML Provider? I can not do it either :(

Thank you.

**Comment by svenwltr** [comment]
Hello @opsrom,

so you want to filter roles that are either `TOTO` *or* starts with `Admin`?

It would look like this:

```yaml
accounts:
  xxx:
    filters:
      IAMRole:
      - "TOTO"
      - type: glob
        value: "Admin*"
```
