### ISSUE TITLE
How to Nuke Manual RDS Snapshot

### ISSUE THREAD

**Issue by pragya-nayak** [rebuy-de/aws-nuke#512]
I am using the target as "RDSSnapshot". This is removing automated snapshot but not the manual one. Could you please suggest if there is any other target name for RDS manual snapshots.

```yaml
resource-types:
  targets:
  - RDSSnapshot
```
