### ISSUE TITLE
Filtering IAM Roles on the 'path' property not working

### ISSUE THREAD

**Issue by dipenj** [rebuy-de/aws-nuke#525]
Filtering IAM Roles based on `Path` property for IAM Roles is not working, using either of the following:-

Using property and regex together:
```
IAMRole:
  - property: Path
    type: regex
    value: /aws-reserved/.*
```

Using property and glob together:
```
IAMRole:    
  - property: Path
    type: glob
    value: /aws-reserved*
```

Nuke fails with the error:
```
level=error msg="UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSReservedSSO_AdministratorAccess_e75a083b411454fb' -  this role is only modifiable by AWS
```
Is there a way to filter IAM Roles based on either of its `path` or `arn`?
