### ISSUE TITLE
Filters seem in error

### ISSUE THREAD

**Issue by neildmorris** [rebuy-de/aws-nuke#53]
aws-nuke deletes items identified in filter in us-east-1, us-east-2, ap-southeast-1, ap-souteast-2

with nuke-config.yml as 

```
regions:
- ap-south-1
- eu-west-2
- eu-west-1
- ap-northeast-2
- ap-northeast-1
- sa-east-1
- ca-central-1
- ap-southeast-1
- ap-southeast-2
- eu-central-1
- us-east-1
- us-east-2
- us-west-1
- us-west-2

account-blacklist:
- "999999999999" # production

accounts:
  "000000000000": # aws-nuke-example
    filters:
      IAMUser:
      - "my-user"
      IAMUserPolicyAttachment:
      - "my-user -> AdministratorAccess"
      IAMUserAccessKey:
      - "my-user -> ABCDEFGHIJKLMNOPQRST
```

output to a text file as aws-nuke -c nuke-config.yml  --profile xyz --force > output.txt 

cat out.txt | grep "would remove" | grep "my-user"

shows would delete IAMUser, IAMUserPolicyAttachment, and IAMUserAccessKey for each of the noted regions above.  

with --no-dry-run it does in fact delete the user and once that is done of courses errors out.

**Comment by svenwltr** [comment]
Hello @neildmorris which version did you use? We had some typos in the configuration, which we fixed (but not released yet). So please make sure the strings (eg `IAMUserPolicyAttachment`) of the output and the config are identical.

**Comment by sabrehagen** [comment]
I am using the config

```
accounts:
  "XXXXXXXXXX":
    filters:
      IamRole:
      - "phxdevelop.jackson.delahunt"
      IamRolePolicyAttachment:
      - "phxdevelop.jackson.delahunt -> AdministratorAccess"

```

But am finding the `IAMRolePolicyAttachment` will be deleted, when I would expect it to be filtered. Is this an issue with my configuration or a bug in the software?

```
ap-southeast-1 - IAMRole - 'phxdevelop.jackson.delahunt' - filtered by config
ap-southeast-1 - IAMRolePolicyAttachment - 'phxdevelop.jackson.delahunt -> AdministratorAccess' - would remove
```
