### ISSUE TITLE
Unable to Nuke ALB and Target Group attached with ALB

### ISSUE THREAD

**Issue by pragya-nayak** [rebuy-de/aws-nuke#553]
I am getting error when AWS-Nuke try to Nuke any Target Group, when Target Group has ALB attached to it. The issue is I am providing both ELBv2LoadBalancer  ELBv2TargetGroup in target but it never picks up ELBv2LoadBalancer to delete ALB. Is there any other target type that I need to provide for ALB and Target Group deletion. I tried with: 
```yaml
targets
  - ELBLoadBalancer
  - ELBv2LoadBalancer
  - ELBv2TargetGroup
``` 

This is a urgent requirement to cleanup the resources in account. Please respond asap.
I am using AWS-Nuke Version : 2.14.0

Thanks in advance.

**Comment by der-eismann** [comment]
Hey @pragya-nayak, sorry for the late reply. Were you able to find a solution for your problem?

If not, please post the rest of your nuke config and the log output to give us a better overview.

**Comment by pragya-nayak** [comment]
Hi @der-eismann I tried to replicate the issue to check if aws-nuke is picking up the ALB for deletion. 
I have deployed an ALB with Lambda as target but aws-nuke only took Target group for deletion and later end up with a failed status that Target Group is currently in use by listener and rule. So it is not deleting ALB and its Target Group.

Here is the config.yml file configuration:
```yml
regions:
  - global
  - us-east-1
  - us-west-2

account-blacklist:
  - "0000000000" # production

resource-types:
  targets:
  - ELBLoadBalancer
  - ELBv2LoadBalancer
  - ELBv2TargetGroup


accounts:
  11111111111:
```

Here is the output : 

![image](https://user-images.githubusercontent.com/58519112/92377264-853fff00-f121-11ea-9725-ec8021dcbd48.png)
