### ISSUE TITLE
If filter applied for one VPC, all other VPCs created get filtered by nuke

### ISSUE THREAD

**Issue by gundkalneha** [rebuy-de/aws-nuke#568]
If filter applied for one VPC, all other VPCs created get filtered by nuke. Yml file content /filter applied is:
      EC2VPC:
        - type: "contains"
        - value: "cldeng"
      EC2Subnet:
        - type: "contains"
        - value: "cldeng"
      EC2InternetGatewayAttachment:
        - type: "contains"
        - value: "cldeng"
      EC2RouteTable:
        - type: "contains"
        - value: "cldeng"
      EC2InternetGateway:
        - type: "contains"
        - value: "cldeng"
      EC2NATGateway:
        - type: "contains"
        - value: "cldeng"
      EC2DHCPOption:
        - type: "contains"
        - value: "cldeng"
      EC2VPCEndpoint:
        - type: "contains"
        - value: "cldeng"
      EC2NetworkACL:
        - type: "contains"
        - value: "cldeng"
      EC2SecurityGroup:
        - type: "contains"
        - value: "cldeng"
      EC2VPCEndpointServiceConfiguration:
        - type: "contains"
        - value: "cldeng"

Nuke Output:

--
539 | us-east-2 - EC2VPC - vpc-09134####575 - [ID: "vpc-091344e####3f575", IsDefault: "false", tag:Name: "delete-me-vpc-1", tag:delete: "me"] - filtered by config
540 | us-east-2 - EC2VPC - vpc-0ba2#####27b07de - [ID: "vpc-0ba23c####27b07de", IsDefault: "false", tag:Name: "delete-me-vpc-2", tag:delete: "me"] - filtered by config
541 | us-east-2 - EC2VPC - vpc-0bad6####9b0722e2 - [ID: "vpc-0bad####9b0722e2", IsDefault: "false", tag:Name: "vpc-use-testvpc"] - filtered by config

**Comment by svenwltr** [comment]
Hello @gundkalneha. That's invalid YAML. It should look like:

```yaml
EC2VPC:
- type: "contains"
  value: "cldeng"
EC2Subnet:
- type: "contains"
  value: "cldeng"
EC2InternetGatewayAttachment:
- type: "contains"
  value: "cldeng"
EC2RouteTable:
- type: "contains"
  value: "cldeng"
EC2InternetGateway:
- type: "contains"
  value: "cldeng"
EC2NATGateway:
- type: "contains"
  value: "cldeng"
EC2DHCPOption:
- type: "contains"
  value: "cldeng"
EC2VPCEndpoint:
- type: "contains"
  value: "cldeng"
EC2NetworkACL:
- type: "contains"
  value: "cldeng"
EC2SecurityGroup:
- type: "contains"
  value: "cldeng"
EC2VPCEndpointServiceConfiguration:
- type: "contains"
  value: "cldeng"
```

**Comment by gundkalneha** [comment]
Thanks @svenwltr, but the VPC filtered with substring matching keyword in VPC names, does not filter and now all VPCs get deleted, even the ones that should not be deleted.

**Comment by gundkalneha** [comment]
YML:
EC2VPC:
- type: "contains"
  value: "cldeng"
EC2Subnet:
- type: "contains"
  value: "cldeng"
EC2InternetGatewayAttachment:
- type: "contains"
  value: "cldeng"
EC2RouteTable:
- type: "contains"
  value: "cldeng"
EC2InternetGateway:
- type: "contains"
  value: "cldeng"
EC2NATGateway:
- type: "contains"
  value: "cldeng"
EC2DHCPOption:
- type: "contains"
  value: "cldeng"
EC2VPCEndpoint:
- type: "contains"
  value: "cldeng"
EC2NetworkACL:
- type: "contains"
  value: "cldeng"
EC2SecurityGroup:
- type: "contains"
  value: "cldeng"
EC2VPCEndpointServiceConfiguration:
- type: "contains"
  value: "cldeng

OUTPUT:
Even VPC with filter applied got deleted. Below logs:

us-west-1 - EC2VPC - vpc-07****38f57a9 - [ID: "vpc-07f6*****7a9", IsDefault: "false", tag:Name: "cerner-delete-me-1"] - removed
--
775 | us-west-2 - EC2Subnet - subnet-04202c*****e32b8d - [DefaultForAz: "false", tag:Name: "cldeng-donot-delete"] - removed
776 | us-west-2 - EC2InternetGatewayAttachment - igw-0b2****1a7500 -> vpc-07a78e*****ca66b - [tag:igw:Name: "cldeng-donot-delete", tag:vpc:Name: "cldeng-donot-delete"] - removed
777 | us-west-2 - EC2VPC - vpc-07a****49ca66b - [ID: "vpc-07a78e6******ca66b", IsDefault: "false", tag:Name: "cldeng-donot-delete"] - removed

**Comment by bjoernhaeuser** [comment]
Hi @gundkalneha 

you can use markdown features to make it easier to read your yaml file. From this is hard to see if this is valid yaml or not. 

If you want to filter based on a property/tag you have to provide that, at least thats what I know:

```
EC2VPC:
- property: "tag:Name"
   type: contains
   value: "cldeng"
EC2InternetGatewayAttachment:
- property: "tag:Vpc:Name"
   type: contains
   value: "cldeng"
```

**Comment by gundkalneha** [comment]
Thank You @bjoernhaeuser.

We now see that VPC with cldeng are retained, but it is failing to delete VPCs with other names. Strangest part is, it deleted 1 VPC without 'cldeng' and retained one more VPC without cldeng as attached in below screenshot.

It successfully deleting 1 resource which does not have 'cldeng' but failing to delete all other resources without 'cldeng'. Attached are the screenshots.

![image](https://user-images.githubusercontent.com/64186490/97543932-ecc24e80-19ee-11eb-9cf2-ff4ee91b09bb.png)
![image](https://user-images.githubusercontent.com/64186490/97545260-bc7baf80-19f0-11eb-91ab-bef1b2b25977.png)
![image](https://user-images.githubusercontent.com/64186490/97545068-7aeb0480-19f0-11eb-9099-e46fe07e0917.png)


Below is the VPC Regex for VPCs and resources to be filtered:
EC2VPC:
```
        - type: "contains"
          value: "aws-controltower"
        - property: "tag:Name"
          type: "contains"
          value: "cldeng"
      EC2Subnet:
        - type: "contains"
          value: "aws-controltower"
        - property: "tag:Name"
          type: "contains"
          value: "cldeng"
      EC2InternetGatewayAttachment:
        - type: "contains"
          value: "aws-controltower"
        - property: "tag:igw:Name"
          type: "contains"
          value: "cldeng"
      EC2InternetGateway:
        - type: "contains"
          value: "aws-controltower"
        - property: "tag:Name"
          type: "contains"
          value: "cldeng"
      EC2VPCEndpoint:
        - type: "contains"
          value: "aws-controltower"
        - property: "tag:Name"
          type: "contains"
          value: "cldeng"
      EC2NetworkACL:
        - type: "contains"
          value: "aws-controltower"
        - property: "Name"
          type: "contains"
          value: "cldeng"
      EC2SecurityGroup:
        - type: "contains"
          value: "aws-controltower"
        - property: "Name"
          type: "contains"
          value: "cldeng"
        - property: "Name"
          type: "contains"
          value: "FMManaged"
      EC2RouteTable:
        - property: "tag:Name"
          type: "contains"
          value: "cldeng"
      EC2DHCPOption:
        - property: "Name"
          type: "contains"
          value : "cldeng"
        - property: "tag:Name"
          type: "contains"
          value: "cldeng"
```
Because of this scenario our code build is failing which is dependent on Nuke.
