### ISSUE TITLE
VPC filter not working, all VPCs deleted

### ISSUE THREAD

**Issue by gundkalneha** [rebuy-de/aws-nuke#569]
VPC filtered with substring matching keyword in VPC names, does not filter and now all VPCs get deleted, even the ones that should not be deleted.

YML File Content:

```
EC2VPC:
- type: "contains"
  value: "cldeng"
EC2Subnet:
- type: "contains"
  value: "cldeng"
EC2InternetGatewayAttachment:
- type: "contains"
  value: "cldeng"
EC2RouteTable:
- type: "contains"
  value: "cldeng"
EC2InternetGateway:
- type: "contains"
  value: "cldeng"
EC2NATGateway:
- type: "contains"
  value: "cldeng"
EC2DHCPOption:
- type: "contains"
  value: "cldeng"
EC2VPCEndpoint:
- type: "contains"
  value: "cldeng"
EC2NetworkACL:
- type: "contains"
  value: "cldeng"
EC2SecurityGroup:
- type: "contains"
  value: "cldeng"
EC2VPCEndpointServiceConfiguration:
- type: "contains"
  value: "cldeng"
```

OUTPUT:
Even VPC with filter applied got deleted. Below logs:

us-west-1 - EC2VPC - vpc-07#####38f57a9 - [ID: "vpc-07f6####7a9", IsDefault: "false", tag:Name: "test-delete-me-1"] - **removed**
775 | us-west-2 - EC2Subnet - subnet-04202c####e32b8d - [DefaultForAz: "false", tag:Name: "**cldeng**-donot-delete"] - removed
776 | us-west-2 - EC2InternetGatewayAttachment - igw-0b2####1a7500 -> vpc-07a78e####ca66b - [tag:igw:Name: "cldeng-donot-delete", tag:vpc:Name: "**cldeng**-donot-delete"] - **removed**
777 | us-west-2 - EC2VPC - vpc-07a#####49ca66b - [ID: "vpc-07a78e6####ca66b", IsDefault: "false", tag:Name: "**cldeng**-donot-delete"] - **removed**
