### ISSUE TITLE
Nuke fails to filter Service catalog products

### ISSUE THREAD

**Issue by dsg9321** [rebuy-de/aws-nuke#584]
aws-nuke fails to filter out Service Catalog products with specific string.Below is the nuke config file to filter out ServiceCatalogProduct with string "donotdelete" as a name of the product and portfolio.

```
regions:
  - us-east-1
account-blacklist:
  - 12345678 # Arbitrary production account id

accounts:
  "9876543210": # Child Account
    filters:
      ServiceCatalogPortfolio:
        - property: "Name"
          type: "contains"
          value : "donotdelete"
        - property: "tag:test"
          value: "donotdelete"
      ServiceCatalogProduct:
        - property: "Name"
          type: "contains"
          value : "donotdelete"
        - property: "tag:test"
          value: "donotdelete"
      ServiceCatalogPrincipalPortfolioAttachment:
        - property: "Name"
          type: "contains"
          value : "donotdelete"
        - property: "tag:test"
          value: "donotdelete"
      ServiceCatalogPortfolioProductAttachment:
        - property: "Name"
          type: "contains"
          value : "donotdelete"
        - property: "tag:test"
          value: "donotdelete"
```
Below are the other configurations that I tried.
```
regions:
  - us-east-1
account-blacklist:
  - 12345678 # Arbitrary production account id

accounts:
  "9876543210": # Child Account
    filters:
      ServiceCatalogConstraintPortfolioAttachment:
        - "donotdelete"
      ServiceCatalogPrincipalPortfolioAttachment:
        - "donotdelete"
      ServiceCatalogPortfolioProductAttachment:
        - "donotdelete"
      ServiceCatalogPortfolio:
        - "donotdelete"
      ServiceCatalogPortfolioShareAttachment:
        - "donotdelete"
      ServiceCatalogTagOptionPortfolioAttachment:
        - "donotdelete"
      ServiceCatalogProduct:
        - "donotdelete"
      ServiceCatalogProvisionedProduct:
        - "donotdelete"
      ServiceCatalogTagOption:
        - "donotdelete"
```

```
regions:
  - us-east-1
account-blacklist:
  - 12345678 # Arbitrary production account id

accounts:
  "9876543210": # Child Account
    filters:
      ServiceCatalogConstraintPortfolioAttachment:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogPrincipalPortfolioAttachment:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogPortfolioProductAttachment:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogPortfolio:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogPortfolioShareAttachment:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogTagOptionPortfolioAttachment:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogProduct:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogProvisionedProduct:
        - type: "contains"
          value: "donotdelete"
      ServiceCatalogTagOption:
        - type: "contains"
          value: "donotdelete"
```

Created Service catalog product with "donotdelete" term in name and attached to the portfolio with term "donotdelete".Attached few roles for the access as well. Nuke with above configuration files failed to filter out products and portfolio with name "donotdelete"

Below are the logs on running nuke with above configuration files.

```
us-east-1 - ServiceCatalogPortfolio - port-sede66zm6h3wo - would remove
us-east-1 - ServiceCatalogPortfolioProductAttachment - prod-ydrxyzcyqjsyw -> port-sede66zm6h3wo - would remove
us-east-1 - ServiceCatalogProduct - prod-ydrxyzcyqjsyw - would remove
us-east-1 - ServiceCatalogPrincipalPortfolioAttachment - arn:aws:iam::9876543210:role/ChildRole -> port-sede66zm6h3wo - would remove
```

Modified filter with product and port id as shown below.Nuke filtered the product successfully.
**Config-file:**
```
...
      ServiceCatalogProduct:
        - "prod-ydrxyzcyqjsyw"
      ServiceCatalogPortfolio:
        - "port-sede66zm6h3wo"
```
**Output:**
```
...
us-east-1 - ServiceCatalogProduct - prod-ydrxyzcyqjsyw - filtered by config
us-east-1 - ServiceCatalogPortfolio - port-sede66zm6h3wo - filtered by config
us-east-1 - ServiceCatalogPortfolioProductAttachment - prod-ydrxyzcyqjsyw -> port-sede66zm6h3wo - would remove
us-east-1 - ServiceCatalogPrincipalPortfolioAttachment - arn:aws:iam::9876543210:role/ChildRole -> port-sede66zm6h3wo - would remove
```

Kindly let me know the procedure to filter out with names.
