### ISSUE TITLE
Multi-Filter Syntax help

### ISSUE THREAD

**Issue by ChaseFreeman17** [rebuy-de/aws-nuke#601]
Is there a way to do a mult-select filter on a single property?

Here are the ways we have tried.

```
      EC2VPC:
      - property: "tag:Name"
        type: contains
        value:
        - "tgw"
        - "99"
        invert: true
```

Or 
```
      EC2VPC:
      - property: "tag:Name"
        type: contains
        value: "tgw"
        invert: true
      - property: "tag:Name"
        type: contains
        value: "99"
        invert: true
```
