### ISSUE TITLE
Adding AWS Budgets

### ISSUE THREAD

**Issue by mrkenkeller** [rebuy-de/aws-nuke#603]
I'm working on adding AWS Budgets to Nuke.

For the `DescribeBudgets` API I need an account number.  I see that for [line  25 of the resource for opsworks user profile](https://github.com/rebuy-de/aws-nuke/blob/main/resources/opsworks-userprofiles.go#L25) uses STS to get the account number.

I copied and pasted (added a print statement for debugging) over to [Budgets branch](https://github.com/StateFarmIns/aws-nuke/blob/add_budgets/resources/budgets.go#L36).

```
	identityOutput, err := sts.New(sess).GetCallerIdentity(nil)
	if err != nil {
		fmt.Printf("sts error: %s \n", err)
		return nil, err
	}
```

It compiles but when I run, it prints the following errors:
```
sts error: service 'sts' is not global, but the session is 
sts error: service 'sts' is not available in region 'u-east-1' 
```
I just copied and pasted and can't figure out how this is different than what is done in opsworks user profile.

It does have me asking is using STS the best way to get the account number?   Is there some way to access the information within the config that I'm missing?

**Comment by mrkenkeller** [comment]
FYI my config - in case it is important:
My config is pretty simple:
```
---
regions:
- "global"
- "u-east-1"

account-blocklist:
- 012345678901

# optional: restrict nuking to these resources
resource-types:
  targets:
  - Budget

accounts:
  123456789012:
    filters:
      Budget: 
        - type: glob
          value: "*billing*"
```
