### ISSUE TITLE
Filter `CloudWatchEventsRule`

### ISSUE THREAD

**Issue by scottschreckengaust** [rebuy-de/aws-nuke#616]
Why won't any of the following filters work?

```yml
       CloudWatchEventsRule:
       - property: "Rule"
         value: "aws-controltower-ConfigComplianceChangeEventRule"
       - property: "Name"
         value: "aws-controltower-ConfigComplianceChangeEventRule"
       - property: "Name"
         value: "Rule: aws-controltower-ConfigComplianceChangeEventRule"
```

Debug output shows the below `awk-nuke --config nuke-config.yml --verbose --target CloudWatchEventsRule`:

```
...
< {"Rules":[{"Arn":"arn:aws:events:us-east-1:000000000000:rule/aws-controltower-ConfigComplianceChangeEventRule", "Description":"CloudWatch Event Rule to send notification on Config Rule compliance changes.", "EventBusName":"default", "EventPattern":"{\"detail-type\":[\"Config Rules Compliance Change\"],\"source\":[\"aws.config\"]}", "Name":"aws-controltower-ConfigComplianceChangeEventRule", "State":"ENABLED"}]}
us-east-1 - CloudWatchEventsRule - Rule: aws-controltower-ConfigComplianceChangeEventRule - would remove
...
```

FYI: Why does using the below work?
```yml
       - "Rule: aws-controltower-ConfigComplianceChangeEventRule"
```
