### ISSUE TITLE
Feature request: Use dateOlderThan on tags which include date/time stamps

### ISSUE THREAD

**Issue by stoimendhristov** [rebuy-de/aws-nuke#636]
My nuke config file is the following:
```
---
regions:
- "us-east-1"

# Accounts not to target
account-blocklist:
- some-account

resource-types:
  targets:
  - RDSInstance

accounts:
  account-to-nuke:
    filters:
      RDSInstance:
        - property: 'tag:expiration_date'
          type: dateOlderThan
          value: 2021-05-12T00:04:52Z
          invert: true
```

I have RDS instances which I tag (upon automatic creation) with `expiration_date: 2021-05-11T00:04:52Z`.

With the above specified config file `aws-nuke` fails with:
```
Error: time: unknown unit "-" in duration "2021-05-12T00:04:52Z"
```

It would be really useful to be able to use `dateOlderThan` on tags which respect time constraints (such as mine from above - `expiration_date`).

Would it be possible to have this implemented please?

Thank you
