### ISSUE TITLE
filtering out EC2DHCPOption for the default VPC

### ISSUE THREAD

**Issue by bentterp** [rebuy-de/aws-nuke#693]
I think we are missing a way of filtering out the EC2DHCPOption for the default VPC.
I have a preset for leaving the normal resources created for the default VPC in place, except for the dhcp option set:
```
presets:
  defaultvpc:
    filters:
      EC2VPC:
      - property: IsDefault
        value: "true"
      EC2InternetGateway:
      - property: DefaultVPC
        value: "true"
      EC2InternetGatewayAttachment:
      - property: DefaultVPC
        value: "true"
      EC2Subnet:
      - property: DefaultVPC
        value: "true"
      EC2RouteTable:
      - property: DefaultVPC
        value: "true"
```
Of course this depends on #691 

But there is nothing which indicates that a DHCP option set is used by the default VPC, so I have nothing to filter on.
