### ISSUE TITLE
S3 bucket filtered by config despite no filter excluding it. 

### ISSUE THREAD

**Issue by estebane-frb** [rebuy-de/aws-nuke#703]
Hello, I have an s3 bucket that is getting "S3Bucket - [Name:"mybucketname"] - filtered by config" despite my yml file not having a filter to prevent this deletion. I have ```aws-nuke version v2.15.0```. Below is my nuke config. Was wondering if there is a known issue.

```
regions:
  - "us-east-1"
  - global

account-blocklist:
  - "YYYYYYYYYYYY"

resource-types:
  excludes:
    - S3Object

accounts:
  "XXXXXXXXXXXX":
    filters:
      CloudTrailTrail:
        - type: "contains"
          contains: "CloudTrail"
      S3Bucket:
        - type: "contains"
          contains: "cloudtrail"
      IAMRolePolicy:
        - type: "contains"
          value: "OrganizationAccountAccessRole"
      IAMRolePolicyAttachment:
        - property: RoleName
          value: "OrganizationAccountAccessRole"
        - "AWSServiceRoleForOrganizations -> AWSOrganizationsServiceTrustPolicy"
        - property: RoleName
          value: "AWSServiceRoleForOrganizations"
        - "AWSServiceRoleForSupport -> AWSSupportServiceRolePolicy"
        - property: RoleName
          value: "AWSServiceRoleForSupport"
        - "AWSServiceRoleForTrustedAdvisor -> AWSTrustedAdvisorServiceRolePolicy"
        - property: RoleName
          value: "AWSServiceRoleForTrustedAdvisor"
```

**Comment by ekristen** [comment]
I would suggest you try the latest release to be sure and if it's still happening provide the output of the command (around the point it says filtered) and the updated configuration. I suspect that it's matching on the S3Bucket contains filter rule, but would need logging output to confirm.

**Comment by estebane-frb** [comment]
Hello I just did an upgrade and it did not help. However, the issue was resolved when I removed the S3Bucket filter above:

```
S3Bucket:
        - type: "contains"
          contains: "cloudtrail"
```

It would appear that there is a bug or edge case happening with this filter where it filters any bucket, not just the ones matching the filter.

**Comment by ekristen** [comment]
@estebane-frb it's possible there's a bug, can you provide the logs of the S3Bucket entry? Could the properties or the tags contain that value "cloudtrail"?

**Comment by ekristen** [comment]
Actually just looking at your configuration now a second time I think it's a config issue.

```yaml
S3Bucket:
  - type: "contains"
    contains: "cloudtrail"
```

should actually be

```yaml
S3Bucket:
  - type: "contains"
    value: "cloudtrail"
```

Can you try updating your configuration and report back?
