### ISSUE TITLE
S3 CreationDate filter

### ISSUE THREAD

**Issue by jamesgeddes** [rebuy-de/aws-nuke#771]
I want to nuke S3 buckets and objects that are older than *x* hours.

I have the following config.
```yml
accounts:
  xxxxxxxxxxxx:
    filters:      # never nuke these resources:
      EC2Instance:
        - property: LaunchTime # EC2 instances that are younger x hours old
          type: dateOlderThan
          value: "100h"
      S3Bucket:
        - property: Name       # S3 buckets that are named "foo"
          value: "foo"
        - property: CreationDate # S3 buckets that are younger x seconds old
          type: dateOlderThan
          value: "100h"
      S3Object:
        - property: Bucket     # S3 objects that are in the bucket "foo"
          value: "foo"
        - property: CreationDate # S3 objects that are younger x seconds old
          type: dateOlderThan
          value: "100h"
```

The EC2Instance dateOlderThan filter works as expected, saving all EC2Instances that are younger than 100 hours.

The S3Bucket and S3Object dateOlderThan filter does not seem to work. For example, I made a bucket named `my-new-bucket-aws-nuke` on April 7, 2022, 16:57:35 (UTC+01:00), however aws-nuke outputs
```
eu-west-2 - S3Bucket - s3://my-new-bucket-aws-nuke - [Name: "my-new-bucket-aws-nuke"] - would remove
```

I see that buckets do have an accessible [CreationDate](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Bucket.html). What am I missing?
