### ISSUE TITLE
Delete all resources by tag, not working

### ISSUE THREAD

**Issue by ukreddy-erwin** [rebuy-de/aws-nuke#784]
I can see the syntax to filter (skip deleting) based on individual resource tags.

Is there anyway to delete all the resources with a specific tag and value?

```
resource-types:
 targets:
 - ELB
 - ELBv2
accounts:
 "accountid":
   filters:
     ELBv2:
     - property: "tag:tracking"
       value: "gitlab"
```

This is skipping the ELBv2 resource with this tag and deleting remaining resources.
But I'm expecting reverse.

Also, instead of providing ELBv2, can we delete all the resources with this tag?

**Comment by der-eismann** [comment]
Hello, you can find information about [inverting filters](https://github.com/rebuy-de/aws-nuke#inverting-filter-results) in the readme.  In your case that would be
```yaml
     - property: "tag:tracking"
       value: "gitlab"
       invert: true
```

Also with 
```yaml
 targets:
 - ELB
 - ELBv2
```

you tell aws-nuke to only nuke these two types of resources. If you want to nuke everything, remove the `targets` part. However you need to add a filter for every resource type, there is no such thing as a global filter because not every resource type supports tags or properties.
