### ISSUE TITLE
New Feature: Re-create Default VPC

### ISSUE THREAD

**Issue by tomvachon** [rebuy-de/aws-nuke#79]
Hi there, 

this removes the default vpc (which we want to keep going).  Since AWS made it easier of late, can the tool issue the create-default-vpc API call at the end for a set of specific regions?

**Comment by svenwltr** [comment]
I think this is out of scope of this application. As the name suggests it is about deleting resources from AWS and not recreating anything. Also we are fans of the Unix philosophy "Write programs that do one thing and do it well.". AFAIS you have two options here:

* Write a script which recreates the VPC after nuking it (`aws-nuke -c nuke.yaml --profile default && aws ec2 create-default-vpc --profile default`).
* Whitelist the VPC by adding this to your config:

```
accounts:
  "000000000000": # your account ID
    filters:
      EC2VPC:
      - "vpc-12378945" # the ID of the default VPC
```

Unfortunately you have to specify the ID for this. We are thinking about improving the whitelisting in general, but we don't have a satisfying proposal for this yet.
