### ISSUE TITLE
Cloudfront Origin Access Identities are not supported by aws-nuke

### ISSUE THREAD

**Issue by XinYang-YXY** [rebuy-de/aws-nuke#808]
Hi, 

when I was running aws_nuke, all resources were removed except the **Cloudfront Origin Access Identities**.  Is this resource supported? Thanks 🙏!

**Comment by der-eismann** [comment]
Hi @XinYang-YXY, thanks for your report! The project lacks support for some resources, because AWS constantly keeps adding them, but [CloudFront OAIs should actually be supported](https://github.com/rebuy-de/aws-nuke/blob/main/resources/cloudfront-origin-access-identities.go). Could you maybe post your nuke-config?

When I run nuke locally it works fine:
```
global - CloudFrontOriginAccessIdentity - [ID: "E2SVXGGGG0XXI3"] - would remove

Do you really want to nuke these resources on the account with the ID 123456789012 and the alias 'my-account'?
Do you want to continue? Enter account alias to continue.
> my-account

global - CloudFrontOriginAccessIdentity - [ID: "E2SVXGGGG0XXI3"] - triggered remove
Removal requested: 1 waiting, 0 failed, 0 skipped, 0 finished

global - CloudFrontOriginAccessIdentity - [ID: "E2SVXGGGG0XXI3"] - waiting
Removal requested: 1 waiting, 0 failed, 0 skipped, 0 finished

global - CloudFrontOriginAccessIdentity - [ID: "E2SVXGGGG0XXI3"] - removed
Removal requested: 0 waiting, 0 failed, 0 skipped, 1 finished
```

It's important that you add the region `global` to your config, as CloudFront resources are not bound to a single region.

**Comment by XinYang-YXY** [comment]
Hi @der-eismann, thanks for the info!

This is strange, I did specify region `global` in my config. My nuke-config is:
```yml
regions:
- ap-southeast-1
- global

account-blacklist:
- "999999999999"

accounts:
  "12XXXXXXXX23":
    filters:
      IAMUser:
      - "aws_nuke"
      IAMUserPolicyAttachment:
      - "aws_nuke -> AdministratorAccess"
      IAMUserAccessKey:
      - "aws_nuke -> AKI3T2XXXXXXXXX23"
``` 

I have 1 Origin access identity in my AWS console, but when I ran nuke locally, it was not detected by nuke.

Note:
I installed aws-nuke by running: `go install github.com/rebuy-de/aws-nuke@latest`
When I ran `aws-nuke version`, I got the following outputs:
```bash
version:     unknown
build date:  unknown
scm hash:    unknown
environment: unknown
```
