### ISSUE TITLE
Allow globs in resource name filters

### ISSUE THREAD

**Issue by mhvelplund** [rebuy-de/aws-nuke#813]
This is not a bug but a feature request :)

Instead of typing endless lists of:

```yaml
      EC2RouteTable:
        - property: tag:ManagedBy
          type: glob
          value: GITO*
      EC2Subnet:
        - property: tag:ManagedBy
          type: glob
          value: GITO*
      EC2VPC:
        - property: tag:ManagedBy
          type: glob
          value: GITO*
```

It would be nice if I could use globs or regexps for resource names as well, e.g.:

```yaml
      "EC2*":
        - property: tag:ManagedBy
          type: glob
          value: GITO*
```
