### ISSUE TITLE
FeatureFlags - Not clear what it is 

### ISSUE THREAD

**Issue by zackriso** [rebuy-de/aws-nuke#818]
Can you please provide more details or information on what is FeatureFlags and how is it different from other options? In the example below: 
---
feature-flags:
  disable-deletion-protection:
    RDSInstance: true
    EC2Instance: true
    CloudformationStack: true
  force-delete-lightsail-addons: true

I noticed that EC2Instance:true is part of the list. However, aws-nuke will for example list running EC2 instances, and they will be flagged as "would remove" with a completely vanilla config file such as below: 

---
regions:
- us-east-1

account-blocklist:
- 1234567890

accounts:
  000111222333:

so what would the feature-flag do if I add EC2Instance:true ?

**Comment by svenwltr** [comment]
Hello. The indentation matters in yaml documents. `EC2Instance: true` is part of `disable-deletion-protection`:

```yaml
feature-flags:
  disable-deletion-protection:
    RDSInstance: true
    EC2Instance: true
    CloudformationStack: true
  force-delete-lightsail-addons: true
```

This means setting `feature-flags` → `disable-deletion-protection` → `RDSInstance` to `true` will disable the deletion protection before removing the EC2 instance.
