### ISSUE TITLE
IAMRole delete failed

### ISSUE THREAD

**Issue by optplx** [rebuy-de/aws-nuke#902]
Hello,

using aws-nuke `latest` docker image (with ID `312d0ebbfe4d`).

I am trying to delete IAM roles using a configuration like below (simplified here for the issue)
```
resource-types:
  targets:
  - IAMRole

presets:
  ignore-aws-nuke:
    filters:
      IAMRole:
      - property: "tag:Ignore-aws-nuke"
         type: exact
         value: true

accounts:
  "xxxxxx":
    presets:
    - ignore-aws-nuke
```

When I run aws-nuke, I get `DeleteConflict: Cannot delete entity, must detach all policies first.`. 

If I understand correctly, I should add filters for all corresponding policy attachments? This is not really easy for my use case, since I will have a lot of filters and each new Role filter should be completed by a policy attachments filter. This feels highly error prone to me

So my question are:
- do I understand correctly?
- if yes would it be acceptable to implement a `force-delete` (or similar) to be able to delete the attachments of the listed IAM roles? I would be glad to discuss a solution with you and work on a PR if so

thanks :)
