### ISSUE TITLE
Verify Nuke Config

### ISSUE THREAD

**Issue by Zethex** [rebuy-de/aws-nuke#942]
Is it possible to have a feature to verify the nuke config file at a basic level?  This can then be incorporated into basic CI/CD pipelines.

I was recently bit when I found out the regex does not support negative matching.

**Comment by leighpascoe** [comment]
If you want to delete resources that satisfy some property, use the `invert: true` config. 
```yaml
      EC2VPC:
      - property: tag:TestID
        type: regex
        value: "[\\d]+"
        invert: true
```
