### ISSUE TITLE
Is there a list of properties to filter on?

### ISSUE THREAD

**Issue by grandstairs** [rebuy-de/aws-nuke#970]
I assume that I any module that returns a [Property](https://github.com/rebuy-de/aws-nuke/blob/392093a5ba8b71d4374950a56a0ebeefc470e37d/pkg/types/properties.go#L9) can be used as a filter property? Is there a list of them somewhere?

```yaml
...
presets:
  example:
    filters:
      SNSTopic:
        - property: ResourceArn
          type: "contains"
          value: "example"
```
